INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('kbuttress0@1und1.de','Karrie Buttress','JcfoKBYAB4k','2019-08-10',1080,'38737 Moose Avenue',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('baymer1@hp.com','Bob Aymer','ZEE54kg','2018-12-21',933,'738 Hagan Lane ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('zboulding2@macromedia.com','Zilvia Boulding','VJyMV1Zat','2019-07-25',730,'758 Old Shore Parkway ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('emollon3@bloglovin.com','Emalee Mollon','XUIeJ693h','2018-11-13',786,'11 Dovetail Junction ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('mmulberry4@cmu.edu','Maria Mulberry','oWspnl','2019-07-20',368,'050 Bowman Alley ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('lby5@mozilla.com','Levey By','GdtcUU','2019-02-12',740,'5 Iowa Avenue ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('beates6@last.fm','Baron Eates','UQw6VeA','2019-05-03',625,'87119 Northland Hill ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('tvink7@fotki.com','Trip Vink','49znXd7haFGz','2019-01-13',3,'6823 Lillian Point ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('bterbeck8@about.me','Boonie Terbeck','unCjJTF7sjs','2019-09-15',781,'43 Marquette Plaza ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('atraviss9@auda.org.au','Alonzo Traviss','dLuVMAg','2018-12-19',339,'5303 Village Green Hill ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('nwitteringa@google.com.br','Natassia Wittering','tQlUG4n','2019-03-24',1085,'67399 Reindahl Place ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('fbrookeb@nba.com','Felice Brooke','s9y9Mcfgy1g','2019-09-27',175,'45 Twin Pines Hill ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('cviccaryc@amazon.co.uk','Carlen Viccary','9qd747vh','2018-12-06',1107,'46 Sheridan Place ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('hgethingsd@sogou.com','Hendrik Gethings','zzN5c4','2018-11-18',344,'73 Kedzie Terrace ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('dgirodiase@stanford.edu','Dunc Girodias','j9QW6GQI','2018-10-14',383,'85509 Ludington Drive ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('btanmanf@smh.com.au','Bibbie Tanman','1aukKNEIneq','2019-05-03',1054,'67 Northwestern Center ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('bbartolettig@simplemachines.org','Barnabas Bartoletti','3chTNtqhoo','2018-12-25',810,'725 Eagle Crest Hill ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('nculliph@fc2.com','Nixie Cullip','2UdKIR2f','2019-04-07',424,'507 Graceland Junction ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('mpimblotti@xing.com','Matilde Pimblott','nGZ8disdg','2019-07-18',875,'92 Gina Park ',0,0);
INSERT INTO users(`email`,`name`,`password`,`registered`,`city_id`,`district`,`lat`,`long`) VALUES ('askurrayj@un.org','Al Skurray','bL9tAf','2018-11-25',62,'8 Ridgeview Trail ',0,0);
